# Generated by Django 4.1.10 on 2023-07-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('channel_title', models.CharField(max_length=200)),
                ('thumbnail_url', models.URLField()),
                ('length', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_label', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='FetchVid.video')),
            ],
        ),
    ]
