# Generated by Django 4.1.10 on 2023-07-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FetchVid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='videoquality',
            options={'managed': True},
        ),
    ]
