# Generated by Django 4.1.10 on 2023-07-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FetchVid', '0002_alter_video_options_alter_videoquality_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoquality',
            options={},
        ),
    ]
