# Generated by Django 4.1.10 on 2023-07-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FetchVid', '0003_alter_videoquality_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
