# Generated by Django 4.1.10 on 2023-07-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FetchVid', '0004_alter_video_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoquality',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FetchVid.video'),
        ),
    ]
