# Generated by Django 4.1.10 on 2023-07-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FetchVid', '0005_alter_videoquality_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoquality',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoquality_set', to='FetchVid.video'),
        ),
    ]
