# Generated by Django 4.1.10 on 2023-07-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FetchVid', '0006_alter_videoquality_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='length',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='format',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='quality_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FetchVid.video'),
        ),
    ]
