# Generated by Django 4.1.10 on 2023-07-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FetchVid', '0007_alter_video_channel_title_alter_video_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='length',
            new_name='duration',
        ),
        migrations.DeleteModel(
            name='VideoQuality',
        ),
    ]
