# Generated by Django 4.1.10 on 2023-07-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FetchVid', '0010_video_m4a_video_mp4_video_webm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='m4a',
        ),
        migrations.RemoveField(
            model_name='video',
            name='mp4',
        ),
        migrations.RemoveField(
            model_name='video',
            name='webm',
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FetchVid.video')),
            ],
        ),
    ]
