# Generated by Django 4.1.10 on 2023-07-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FetchVid', '0011_remove_video_m4a_remove_video_mp4_remove_video_webm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='VideoQuality',
        ),
    ]
